---
identifier: "CVE-2021-41198"
identifiers:
- "CVE-2021-41198"
- "GHSA-2p25-55c9-h58q"
package_slug: "pypi/tensorflow"
title: "Overflow/crash in `tf.tile` when tiling tensor is large"
description: "If `tf.tile` is called with a large input argument then the TensorFlow
  process will crash due to a `CHECK`-failure caused by an overflow.\n\n```python\nimport
  tensorflow as tf\nimport numpy as np\ntf.keras.backend.tile(x=np.ones((1,1,1)),
  n=[100000000,100000000, 100000000])\n```\n\nThe number of elements in the output
  tensor is too much for the `int64_t` type and the overflow is detected via a `CHECK`
  statement. This aborts the process."
date: "2024-11-13"
pubdate: "2021-11-10"
affected_range: ">=2.6.0,<2.6.1||>=2.5.0,<2.5.2||<2.4.4"
fixed_versions:
- "2.6.1"
- "2.5.2"
- "2.4.4"
affected_versions: "All versions before 2.4.4, all versions starting from 2.5.0 before
  2.5.2, all versions starting from 2.6.0 before 2.6.1"
not_impacted: "All versions starting from 2.4.4 before 2.5.0, all versions starting
  from 2.5.2 before 2.6.0, all versions starting from 2.6.1"
solution: "Upgrade to versions 2.4.4, 2.5.2, 2.6.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-41198"
- "https://github.com/advisories/GHSA-2p25-55c9-h58q"
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2p25-55c9-h58q"
- "https://github.com/tensorflow/tensorflow/issues/46911"
- "https://github.com/tensorflow/tensorflow/commit/9294094df6fea79271778eb7e7ae1bad8b5ef98f"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-608.yaml"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-806.yaml"
- "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-391.yaml"
- "https://github.com/tensorflow/tensorflow"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "66de051f-879c-4e7e-ac06-fd2d0fc8374e"
cwe_ids:
- "CWE-190"
- "CWE-937"
- "CWE-1035"
