---
identifier: "CVE-2022-23582"
identifiers:
- "CVE-2022-23582"
- "GHSA-4j82-5ccr-4r8v"
package_slug: "pypi/tensorflow"
title: "Reachable Assertion"
description: "Tensorflow is an Open Source Machine Learning Framework. A malicious
  user can cause a denial of service by altering a `SavedModel` such that `TensorByteSize`
  would trigger `CHECK` failures. `TensorShape` constructor throws a `CHECK`-fail
  if shape is partial or has a number of elements that would overflow the size of
  an `int`. The `PartialTensorShape` constructor instead does not cause a `CHECK`-abort
  if the shape is partial, which is exactly what this function needs to be able to
  return `-1`. The fix will be included in TensorFlow We will also cherrypick this
  commit on TensorFlow, TensorFlow, and TensorFlow, as these are also affected and
  still in supported range."
date: "2022-02-10"
pubdate: "2022-02-04"
affected_range: "<=2.5.2||>=2.6.0,<=2.6.2||==2.7.0"
fixed_versions:
- "2.5.3"
- "2.6.3"
- "2.7.1"
affected_versions: "All versions up to 2.5.2, all versions starting from 2.6.0 up
  to 2.6.2, version 2.7.0"
not_impacted: "All versions after 2.5.2 before 2.6.0, all versions after 2.6.2 before
  2.7.0, all versions after 2.7.0"
solution: "Upgrade to versions 2.5.3, 2.6.3, 2.7.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2022-23582"
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-4j82-5ccr-4r8v"
- "https://github.com/tensorflow/tensorflow/commit/c2426bba00a01de6913738df8fa78e0215fcce02"
- "https://github.com/tensorflow/tensorflow/blob/a1320ec1eac186da1d03f033109191f715b2b130/tensorflow/core/framework/attr_value_util.cc#L46-L50"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "b8c5f2f5-261e-4763-9a4a-f7eecb3132cf"
cwe_ids:
- "CWE-1035"
- "CWE-617"
- "CWE-937"
