---
identifier: "CVE-2022-41883"
identifiers:
- "CVE-2022-41883"
- "GHSA-w58w-79xv-6vcj"
package_slug: "pypi/tensorflow"
title: "Out-of-bounds Read"
description: "TensorFlow is an open source platform for machine learning. When ops
  that have specified input sizes receive a differing number of inputs, the executor
  will crash. We have patched the issue in GitHub commit f5381e0e10b5a61344109c1b7c174c68110f7629.
  The fix will be included in TensorFlow 2.11. We will also cherrypick this commit
  on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and
  still in supported range."
date: "2022-11-23"
pubdate: "2022-11-18"
affected_range: "==2.10.0"
fixed_versions:
- "2.10.1"
affected_versions: "Version 2.10.0"
not_impacted: "All versions before 2.10.0, all versions after 2.10.0"
solution: "Upgrade to version 2.10.1 or above."
urls:
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-w58w-79xv-6vcj"
- "https://nvd.nist.gov/vuln/detail/CVE-2022-41883"
- "https://github.com/tensorflow/tensorflow/commit/f5381e0e10b5a61344109c1b7c174c68110f7629"
- "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/dynamic_stitch_op.cc"
- "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/data_flow_ops.cc"
- "https://github.com/advisories/GHSA-w58w-79xv-6vcj"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "b63fb40b-305f-4015-bfb7-1ec49ff2913c"
cwe_ids:
- "CWE-1035"
- "CWE-125"
- "CWE-937"
