---
identifier: "CVE-2022-40899"
identifiers:
- "CVE-2022-40899"
- "GHSA-v3c5-jqr6-7qm8"
package_slug: "pypi/future"
title: "Python Charmers Future denial of service vulnerability"
description: "An issue discovered in Python Charmers Future 0.18.2 and earlier allows
  remote attackers to cause a denial of service via crafted Set-Cookie header from
  malicious web server. This issue has been patched in version 0.18.3."
date: "2024-09-20"
pubdate: "2022-12-23"
affected_range: "<0.18.3"
fixed_versions:
- "0.18.3"
affected_versions: "All versions before 0.18.3"
not_impacted: "All versions starting from 0.18.3"
solution: "Upgrade to version 0.18.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2022-40899"
- "https://github.com/advisories/GHSA-v3c5-jqr6-7qm8"
- "https://github.com/PythonCharmers/python-future/pull/610"
- "https://github.com/python/cpython/pull/17157"
- "https://github.com/PythonCharmers/python-future/commit/c91d70b34ef0402aef3e9d04364ba98509dca76f"
- "https://github.com/PythonCharmers/python-future"
- "https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215"
- "https://github.com/pypa/advisory-database/tree/main/vulns/future/PYSEC-2022-42991.yaml"
- "https://pypi.org/project/future"
- "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "59f72dd3-88c1-47e8-9757-2e68086121cf"
cwe_ids:
- "CWE-937"
- "CWE-1035"
