---
identifier: "CVE-2020-26244"
identifiers:
- "CVE-2020-26244"
- "GHSA-4fjv-pmhg-3rfg"
package_slug: "pypi/oic"
title: "Multiple cryptographic issues in Python oic"
description: "* Client implementations using this library"
date: "2024-10-07"
pubdate: "2020-12-04"
affected_range: "<1.2.1"
fixed_versions:
- "1.2.1"
affected_versions: "All versions before 1.2.1"
not_impacted: "All versions starting from 1.2.1"
solution: "Upgrade to version 1.2.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-26244"
- "https://github.com/advisories/GHSA-4fjv-pmhg-3rfg"
- "https://github.com/OpenIDC/pyoidc/security/advisories/GHSA-4fjv-pmhg-3rfg"
- "https://github.com/OpenIDC/pyoidc/commit/62f8d753fa17c8b1f29f8be639cf0b33afb02498"
- "https://github.com/OpenIDC/pyoidc"
- "https://github.com/OpenIDC/pyoidc/releases/tag/1.2.1"
- "https://github.com/pypa/advisory-database/tree/main/vulns/oic/PYSEC-2020-69.yaml"
- "https://pypi.org/project/oic"
cvss_v2: "AV:N/AC:M/Au:S/C:P/I:P/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:N"
uuid: "449091b8-538d-438f-87b6-cc21904b6591"
cwe_ids:
- "CWE-325"
- "CWE-347"
- "CWE-937"
- "CWE-1035"
