---
identifier: "CVE-2018-7206"
identifiers:
- "CVE-2018-7206"
- "GHSA-8x3m-m3x9-54fj"
package_slug: "pypi/oauthenticator"
title: "JupyterHub OAuthenticator elevation of privilege"
description: "An issue was discovered in Project Jupyter JupyterHub OAuthenticator.
  When using JupyterHub with a GitLab allowlist for access control, group membership
  is not checked correctly, allowing members that are not in the allowlist to create
  accounts on the Hub."
date: "2024-10-03"
pubdate: "2022-05-13"
affected_range: ">=0.6,<0.6.2||>=0.7,<0.7.3"
fixed_versions:
- "0.6.2"
- "0.7.3"
affected_versions: "All versions starting from 0.6 before 0.6.2, all versions starting
  from 0.7 before 0.7.3"
not_impacted: "All versions before 0.6, all versions starting from 0.6.2 before 0.7,
  all versions starting from 0.7.3"
solution: "Upgrade to versions 0.6.2, 0.7.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-7206"
- "https://github.com/advisories/GHSA-8x3m-m3x9-54fj"
- "https://github.com/jupyterhub/oauthenticator/commit/1845c0e4b1bff3462c91c3108c85205acd3c75a2"
- "https://blog.jupyter.org/security-fix-for-jupyterhub-gitlab-oauthenticator-7b14571d1f76"
- "https://github.com/jupyterhub/oauthenticator"
- "https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16"
- "https://github.com/pypa/advisory-database/tree/main/vulns/oauthenticator/PYSEC-2018-68.yaml"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "7f4d0784-970e-4d5d-bcd5-8464aea52e08"
cwe_ids:
- "CWE-937"
- "CWE-1035"
