---
identifier: "CVE-2020-14343"
identifiers:
- "CVE-2020-14343"
- "GHSA-8q59-q68h-6hv4"
package_slug: "pypi/PyYAML"
title: "Improper Input Validation in PyYAML"
description: "A vulnerability was discovered in the PyYAML library in versions before
  5.4, where it is susceptible to arbitrary code execution when it processes untrusted
  YAML files through the full_load method or with the FullLoader loader. Applications
  that use the library to process untrusted input may be vulnerable to this flaw.
  This flaw allows an attacker to execute arbitrary code on the system by abusing
  the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747."
date: "2024-10-25"
pubdate: "2021-03-25"
affected_range: "<5.4"
fixed_versions:
- "5.4"
affected_versions: "All versions before 5.4"
not_impacted: "All versions starting from 5.4"
solution: "Upgrade to version 5.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-14343"
- "https://github.com/advisories/GHSA-8q59-q68h-6hv4"
- "https://github.com/SeldonIO/seldon-core/issues/2252"
- "https://github.com/yaml/pyyaml/issues/420"
- "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966"
- "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
- "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
- "https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml"
- "https://github.com/yaml/pyyaml"
- "https://pypi.org/project/PyYAML"
- "https://www.oracle.com/security-alerts/cpuapr2022.html"
- "https://www.oracle.com/security-alerts/cpujul2022.html"
cvss_v2: "AV:N/AC:L/Au:N/C:C/I:C/A:C"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "ef6843ae-ccfb-4ba7-9c9b-65310b620cd2"
cwe_ids:
- "CWE-20"
- "CWE-937"
- "CWE-1035"
