---
identifier: "CVE-2019-20477"
identifiers:
- "GHSA-3pqx-4fqf-j49f"
- "CVE-2019-20477"
package_slug: "pypi/PyYAML"
title: "Deserialization of Untrusted Data"
description: "PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and
  load_all functions because of a class deserialization issue, e.g., Popen is a class
  in the subprocess module. NOTE: this issue exists because of an incomplete fix for
  CVE-2017-18342."
date: "2022-01-04"
pubdate: "2021-04-20"
affected_range: ">=5.1,<5.2"
fixed_versions:
- "5.2"
affected_versions: "All versions starting from 5.1 before 5.2"
not_impacted: "All versions before 5.1, all versions starting from 5.2"
solution: "Upgrade to version 5.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-20477"
- "https://github.com/yaml/pyyaml/blob/master/CHANGES"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/"
- "https://www.exploit-db.com/download/47655"
- "https://github.com/advisories/GHSA-3pqx-4fqf-j49f"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "43a0466c-7d41-47b6-aafa-f6c2cfaaef4d"
cwe_ids:
- "CWE-1035"
- "CWE-502"
- "CWE-937"
